### ISSUE TITLE
Works Great for Functions, Not for Classes

### ISSUE THREAD

**Issue by shellscape** [kevinconway/Modelo.js#25]
The example in the README works wonderfully. However, if I change those `function` definitions to `class` definitions, the world explodes:

```js
    class MixinOne {}
    class MixinTwo {}

    class Combined {}
    modelo.inherits(Combined, MixinOne, MixinTwo);

    var instance = new Combined();
```

Results in:

```
L29: TypeError: Cannot assign to read only property 'prototype' of function 'class Combined {}'
```

This may be a result of something in how `class` is handled specially, but after digging on the googs for a while I couldn't turn anything up. Curiously, if `function Combined() {}` is used, but the other classes use a `class` def, there's no error.

**Comment by kevinconway** [comment]
It appears to be related to some subtle differences in how `class` and `function` manage the `prototype` object. For example:
```javascript
class C{}
function F(){}

console.log(Object.getOwnPropertyDescriptor(C, "prototype")
console.log(Object.getOwnPropertyDescriptor(F, "prototype")
```
It seems as though `class` results in a `prototype` property that has a `writable` bit set to `false` which differs from what the function syntax creates. The result is that the current strategy of replacing the `prototype` attribute with an assignment fails.

It looks like the same ECMA draft that brought in `class` also brought in `Object.setProtototypeOf` and `Object.defineProperty` which could replace the assignment statements [here](https://github.com/kevinconway/Modelo.js/blob/master/modelo/modelo.js#L126). The node provided `utils.inherits`, from which this project was originally inspired, has [moved to using these methods](https://github.com/nodejs/node/blob/master/lib/util.js#L312) for those same assignments.

I did a quick test in the browser console and it would appear that the `inherits` function does not error once those two assignments are replaced. It's possible this is all that needs to happen in order to support more recent ECMA implementations but I'm not confident, yet, that things like `static` or private fields would work correctly. None of these features existed when this project was created and, as a result, there aren't any tests that would show whether or not these features work as expected after inheritance. Additionally, the `defineProperty` and `setProtototypeOf` functions would need solid polyfills embedded in the project in order to retain compatibility with any "legacy" use cases since the project was designed to work in older environments.

I'm curious to hear your perspective on something like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Mix-ins which appears to provide the same sort of behaviour but with a bit more native of a syntax if you're already using `class`. Do you think that would cover your use case or is there something, still, that this project provides that the class-style mixins would not?

**Comment by shellscape** [comment]
@kevinconway thanks for the response. The mixins approach does satisfy _most_ of my requirements, though I'm partial to this other mozilla implementation https://hacks.mozilla.org/2015/08/es6-in-depth-subclassing/. The caveat with that approach is `super`. With mixins `super` rarely, if ever, functions as expected and it depends largely upon which mixin implementation is used. I haven't found one yet that left the method chain (or constructor chain) intact. But that may be a straight up limitation to mixins for that purpose.

**Comment by kevinconway** [comment]
Yeah, I don't know that the `super` problem ever goes away. Even this library attempts to avoid the issue by suggesting that:
> when using multiple inheritance, the 'super_' attribute should be avoided in favour of calling the target prototype directly if the form of <Constructor>.prototype.<method>.call(this, ...) or <Constructor>.prototype.<method>.apply(this, ...).

Depending on what kind of behaviour you're looking for from `super`, it might very well be an inherent difficulty of using multiple inheritance or mix-ins. For example, this project makes the choice that _all_ constructor functions in the inheritance graph are executed when you create a new instance. The only way to accomplish this is to break from the JS notion of `constructor` and create a [new function that composites](https://github.com/kevinconway/Modelo.js/blob/master/modelo/modelo.js#L88) all of the inherited constructors. This is what breaks the usage of the built-in `isInstance` since it only inspects the `constructor` attribute and is also why the project strongly encourages use of objects for constructor input so that there is a single, uniform input that can be given to all inherited constructors. All of these are notably different from systems like Python that also support multiple inheritance but require a certain level of cooperation between constructors through clever use of `super`.

Method calls raise a similar complication with respect to cooperative `super` usage. Most of the use cases for mix-ins are for isolated, unique functionality that can be injected into any arbitrary object. In the case where one or more mix-ins define the same methods, or when the inheriting object extends a method from one or more mix-ins, there needs to be some process for resolving which definition of the method receives the call. ES6 classes helpfully enforce a linear inheritance order so that you don't necessarily need to worry about things like [method resolution order](https://en.wikipedia.org/wiki/C3_linearization) but triggering anything more than the first matching method call requires usage of `super` in that method which most mix-ins don't do. Additionally, every method of the same name would need to have a `super` invocation in order to continue unraveling the chain until you hit the base object which would need special support for performing a `NOP` for all calls to prevent a "method not found" type of error.

I'm not sure how closely this maps to the challenges you're having with mix-in styles but these are some of the issues I've run into in the past and some of the motivations for the design of this project. At this point I'd say that this library is probably not what you want for your project even if we added `class` support but I'm happy to keep the issue open if you want to dig deeper into `super` related issues.

**Comment by shellscape** [comment]
I think you've gone above an beyond in explaining what the pitfalls are, and some possible remedies for them in this issue. Many thanks for that. I honestly don't have anything to add beyond what you've replied with - well done.

Going to close this one as I'm pretty confident anyone else stopping by with the same concerns will have their answer in this issue. Cheers.
